version: "3.9"

services:
  ################################################################
  # SQL SERVER IDENTITY
  ################################################################
  sqlserver-identity:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-identity
    environment:
      - SA_PASSWORD=P@ssw0rd123!
      - ACCEPT_EULA=Y
    ports:
      - "1436:1433"
    volumes:
      - sqlidentityvolume:/var/opt/mssql
    networks:
      - reseau

  ################################################################
  # SQL SERVER PATIENT
  ################################################################
  sqlserver-patient:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-patient
    environment:
      - SA_PASSWORD=P@ssw0rd123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlpatientvolume:/data/db
    networks:
      - reseau

  ################################################################
  # MONGODB
  ################################################################
  mongodb-notes:
    image: mongo:6.0
    container_name: mongodb-notes
    ports:
      - "27017:27017"
    volumes:
      - mongovolume:/data/db
    networks:
      - reseau

  ################################################################
  # IDENTITY API
  ################################################################
  identityapi:
    build:
      context: .
      dockerfile: IdentityAPI/Dockerfile
    container_name: identityapi
    ports:
      - "7233:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver-identity,1433;Database=IdentityDb;User Id=sa;Password=P@ssw0rd123!;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Jwt__Key=MediLaboSecretForAuthentication123456@!/*
      - Jwt__Issuer=MediLaboIssuer
      - Jwt__Audience=MediLaboAudience
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - sqlserver-identity
    networks:
      - reseau

  ################################################################
  # PATIENTS API
  ################################################################
  patientsapi:
    build:
      context: .
      dockerfile: PatientsAPI/Dockerfile
    container_name: patientsapi
    ports:
      - "7242:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver-patient,1433;Database=PatientsDb;User Id=sa;Password=P@ssw0rd123!;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Jwt__Key=MediLaboSecretForAuthentication123456@!/*
      - Jwt__Issuer=MediLaboIssuer
      - Jwt__Audience=MediLaboAudience
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - sqlserver-patient
      - identityapi
    networks:
      - reseau

  ################################################################
  # NOTES API
  ################################################################
  notesapi:
    build:
      context: .
      dockerfile: NotesApi/Dockerfile
    container_name: notesapi
    ports:
      - "7148:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongodb-notes:27017
      - MongoDbSettings__DatabaseName=NotesDB
      - MongoDbSettings__CollectionName=Notes
      - Jwt__Key=MediLaboSecretForAuthentication123456@!/*
      - Jwt__Issuer=MediLaboIssuer
      - Jwt__Audience=MediLaboAudience
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - mongodb-notes
      - identityapi
    networks:
      - reseau

  ################################################################
  # DIABETE API
  ################################################################
  diabeteapi:
    build:
      context: .
      dockerfile: DiabeteAPI/Dockerfile
    container_name: diabeteapi
    ports:
      - "7246:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=MediLaboSecretForAuthentication123456@!/*
      - Jwt__Issuer=MediLaboIssuer
      - Jwt__Audience=MediLaboAudience
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - patientsapi
      - notesapi
    networks:
      - reseau

  ################################################################
  # GATEWAY
  ################################################################
  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    container_name: gateway
    ports:
      - "7258:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=MediLaboSecretForAuthentication123456@!/*
      - Jwt__Issuer=MediLaboIssuer
      - Jwt__Audience=MediLaboAudience
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - patientsapi
      - notesapi
      - diabeteapi
      - identityapi
    networks:
      - reseau

  ################################################################
  # FRONTEND
  ################################################################
  frontendmvc:
    build:
      context: .
      dockerfile: FrontendMVC/Dockerfile
    container_name: frontendmvc
    ports:
      - "7000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - gateway
    networks:
      - reseau

networks:
  reseau:
    driver: bridge 
    name: reseau

volumes:
  sqlpatientvolume:
  sqlidentityvolume:
  mongovolume: